Documentation, demo, minor bug fixes
SquadHouseDev/SquadHouse pull request #63
Opened 2021-04-12 23:22 UTC by henrylao

- Applied minor bug fixes in the MultiViewAdapter
- Added documentation of model / backend design
- Add documentation of FollowingActivity class usage

2021-04-13 01:11 UTC, wesley-hsieh approved these changes

2021-04-13 01:11 UTC, wesley-hsieh approved these changes
there's some merge conf

2021-04-13 01:12 UTC, wesley-hsieh requested changes
there's some erros in the AndroidManifest.xml

2021-04-14 17:10 UTC, henrylao reviewed
New line difference

2021-04-14 18:16 UTC, wesley-hsieh approved these changes

2021-04-14 18:16 UTC, merged