Add RoomRoute and verified method of querying for RoomRoute availability
SquadHouseDev/SquadHouse pull request #65
Opened 2021-04-14 21:17 UTC by henrylao

Dev log:  https://github.com/SquadHouseDev/SquadHouse/issues/59

2021-04-15 03:49 UTC, wesley-hsieh approved these changes

2021-04-15 03:50 UTC, wesley-hsieh requested changes
some isuse in homeactivity

2021-04-15 15:05 UTC, henrylao commented
just fixed the issue, added the querying afterwards

2021-04-17 00:03 UTC, wesley-hsieh approved these changes

2021-04-17 00:03 UTC, merged